version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    env_file: .env
    volumes:
      - ".:/go/app:cached"
    command: ["go", "run", "main.go"]